services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  celery-worker:
    build: .
    command: celery -A tasks.celery_app worker -l info -c 4
    env_file: .env
    volumes:
      - .:/app

  celery-beat:
    build: .
    command: celery -A tasks.celery_app beat -l info
    env_file: .env
    volumes:
      - .:/app
